data_path: /home/cally/Code/FundamentaLLM/data/raw/shakespeare/shakespeare1mil.txt
train_split: 0.8
sequence_length: 256
batch_size: 16
num_workers: 4
learning_rate: 0.001
optimizer: adamw
optimizer_eps: 1.0e-08
optimizer_weight_decay: 0.01
adam_beta1: 0.9
adam_beta2: 0.999
scheduler: linear_warmup
warmup_steps: 500
total_steps: null
min_lr_ratio: 0.1
train_steps_per_epoch: null
max_grad_norm: 1.0
accumulation_steps: 1
gradient_accumulation_steps: null
gradient_clip_norm: null
gradient_checkpointing: false
mixed_precision: false
num_epochs: 10
max_epochs: null
max_steps: null
eval_steps: 100
dropout: 0.1
checkpoint_dir: /home/cally/Code/FundamentaLLM/models/large_model_quick
checkpoint_keep_last: 3
save_every_n_steps: null
save_every_n_epochs: 1
early_stopping_patience: 0
early_stopping_metric: val_loss
early_stopping_mode: min
early_stopping_min_delta: 0.0
seed: 42
deterministic: true
device: cuda
